### ISSUE TITLE
TLS not used in pg client for crate out

### ISSUE THREAD

**Issue by at-besa** [heyoka/faxe#10]
when fetching the columns if needed for the crate out the used pg client does not respect the TLS settings by environment.
Maybe also add separate crate_out configuration params for dfs script to set external config for the pg client used in there.

https://github.com/heyoka/faxe/blob/6494841485407c8a3d2ac457cacc1f2e9dd34677/apps/faxe/src/components/esp_crate_out.erl#L502

**Comment by heyoka** [comment]
Good catch! Thanks for that,
admittedly using an extra client to fetch the columns seems not to be the cleanest solution, but the http client in the node is used for writing only, so there was no choice.
Regarding extra config params for the pg client, if I understand your request correctly, the pg client does use the config params for the connections to crate, just the tls setting is missing I think

**Comment by heyoka** [comment]
To be more precise on the question "What connection parameters does this pg client use ?" : It uses the same params as the crate_out node which gets them from the config (In this case these are the FAXE_CRATE_HTTP_* env settings), where each setting is possible overwritten with the dedicated node parameter in DFS.

**Comment by at-besa** [comment]
yeah just the tls setting is missing, which results in the error some lines below when trying to write into crate without having columns defined in the crate_out node.
we tried using separate and overwritten parameters and identified the behaviour that the client is not respecting the tls setting on the target db. Though i asked for separate connection settings for this specific out node as the http tls and the pgsql tls can differ. i.e. http tls is on but pg tls is off.

also small fun fact the dfs node params also have a small difference:
 |crate_query()
 .ssl(true)
 
 |crate_out()
 .tls(true)
 
 and with the environment settings its the string "on" and "off" for these which is also little confusing

**Comment by heyoka** [comment]
I see, then maybe it would be better to use the FAXE_CRATE_* (for pg cliens) settiings as a default. I will think about how we make this most flexible without the need for too many additional config settings.

**Comment by heyoka** [comment]
> also small fun fact the dfs node params also have a small difference:
> |crate_query()
> .ssl(true)
>
> |crate_out()
> .tls(true)

yeah, I think about changing this for a long time now, did not find the time though
[https://github.com/heyoka/faxe/issues/13](https://github.com/heyoka/faxe/issues/13)

> and with the environment settings its the string "on" and "off" for these which is also little confusing

probably will not change this anytime soon
