### ISSUE TITLE
Additional info on project?

### ISSUE THREAD

**Issue by ioolkos** [heyoka/faxe#7]
@heyoka This looks like an interesting Erlang project :)
Do you have additional information available somewhere? (just on what it is, what the plan/roadmap is or similar). Is it comparable to Elixir Broadway?

Thanks & apologies for opening a non-technical issue, feel free to ignore if inappropriate.

**Comment by heyoka** [comment]
Hi ioolkos, thank you for your interest in this project ;)
We have a user documentation [here](https://github.com/heyoka/faxe-docs), you can read the Markdown files under /doc without downloading the html files.
Faxe is built around a self-written dataflow engine, where computing nodes can be arranged in a DAG that form dataflows.
It is built with streaming time series data in mind and has many features which support this.
To build these DAGs we use a dsl called [DFS](https://github.com/heyoka/dfs), which is heavily inspired by Influxdata's TICK script. But the DAGs could also be build via a UI (like node-red).

Faxe has many built in nodes for different tasks such as: s7read,modbus, simple tcp, mqtt_publish and subscribe, amqp_*, windowing nodes, aggregations, tranformation, etc. Furthermore we can write custom nodes in python, that can be used like any other built in node.

We use faxe to collect, process and write industrial sensor data, therefore we run faxe instances at every stage of our data-pipeline, from the edge IPC (with balena) where data collection takes place, messaging (mqtt, amqp), to the end of the pipeline in the cloud where we process data and do some ML as well as writing this data into a time series DB. 

I started this project in late 2016, at this time I could not find any suitable libraries such as Elixir Gen_Stage, so I wrote it by myself, if I started today I would definitly use such a library. I do not know Broadway in depth, but I would say that Broadway is more general than faxe.
There are of course many things, that could be implemented better or more flexible, maybe some parts would benefit from a rewrite, but overall faxe serves us very well so far.

If you have more questions please feel free to ask them.
Alex

**Comment by ioolkos** [comment]
@heyoka thanks for your answer, great to hear this works well for you!
